import type { Project, Video } from "./api";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Product Launch Reel — September",
    totalVideos: 6,
    readyVideos: 4,
    processingVideos: 1,
    failedVideos: 1,
    queuedVideos: 0,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    active: true,
  },
  {
    id: "proj-2",
    name: "Founder Talking Head Shorts",
    totalVideos: 12,
    readyVideos: 12,
    processingVideos: 0,
    failedVideos: 0,
    queuedVideos: 0,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    active: false,
  },
  {
    id: "proj-3",
    name: "Weekly Tips Batch #4",
    totalVideos: 4,
    readyVideos: 0,
    processingVideos: 0,
    failedVideos: 0,
    queuedVideos: 4,
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    active: false,
  },
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: "vid-1",
    filename: "01_intro_hook_raw.mp4",
    duration: 48.2,
    width: 1080,
    height: 1920,
    status: "READY",
    progress: 100,
    currentStage: "READY",
    outputUrl: "https://example.com/output_01.mp4",
    projectId: "proj-1",
  },
  {
    id: "vid-2",
    filename: "02_feature_breakdown.mp4",
    duration: 62.5,
    width: 1080,
    height: 1920,
    status: "RENDERING",
    progress: 88,
    currentStage: "RENDERING",
    projectId: "proj-1",
  },
  {
    id: "vid-3",
    filename: "03_call_to_action.mp4",
    duration: 35.0,
    width: 1080,
    height: 1920,
    status: "FAILED",
    progress: 42,
    currentStage: "TRANSCRIBING",
    errorMessage: "Audio stream contained clipping; speech recognition failed.",
    projectId: "proj-1",
  },
];
